version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - SECRET_KEY=supersecretkey
      - DATABASE_URL=postgres://user:pass@db:5432/soundboard
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: soundboard
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
