# Étape 1 : Build
FROM node:20 AS builder

WORKDIR /app
COPY frontend/ .
RUN npm install && npm run build

# Étape 2 : Serveur statique (nginx)
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
